[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:roadrunner]
command=rr serve -c /usr/local/etc/.rr.yml -w /var/www/html
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:queue-worker]
command=php -d memory_limit=-1 -d max_execution_time=0 artisan queue:work --verbose --tries=2 --timeout=10 --queue=auth,default
directory=/var/www/html
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
numprocs=1

[include]
files=/etc/supervisor/conf.d/includes/*.conf
