location /admin {
    fastcgi_pass app;

    fastcgi_keep_conn on;

    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param QUERY_STRING $query_string;
    include fastcgi_params;
}
