location /api {
    fastcgi_pass app;

    fastcgi_cache fastcgicache;
    fastcgi_cache_bypass $no_cache_request_method $http_authorization;
    fastcgi_no_cache $no_cache_request_method $http_authorization;
    fastcgi_cache_valid 1d;

    fastcgi_keep_conn on;

    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param QUERY_STRING $query_string;
    include fastcgi_params;

    add_header Cache-Control "public, max-age=30";
}
